import { opts } from '@/lib/admin/common/fields';
import type { ResourceDefinition } from '@/lib/admin/common/resource';

const STATUS_OPTIONS = opts(
  ['pending', 'Pending'],
  ['approved', 'Approved'],
  ['completed', 'Completed'],
  ['failed', 'Failed'],
  ['cancelled', 'Cancelled'],
  ['refunded', 'Refunded'],
  ['partially_refunded', 'Partially refunded'],
);

export const paymentsDefinition: ResourceDefinition = {
  key: 'payments',
  label: 'Payments',
  singular: 'Payment',
  description: 'Square payment attempts and provider state.',
  group: 'Payments',
  basePath: '/admin/payments',
  apiPath: 'payments',
  permission: 'orders',
  titleKey: 'providerPaymentId',
  idPrefix: 'payment',
  seed: () => [],
  searchFields: ['providerPaymentId', 'providerOrderId', 'checkoutIntentId', 'status'],
  defaultSort: { key: 'createdAt', direction: 'desc' },
  filters: [{ key: 'status', label: 'Status', options: STATUS_OPTIONS }],
  columns: [
    { key: 'providerPaymentId', label: 'Square payment', type: 'title', sortable: true },
    { key: 'providerOrderId', label: 'Square order', type: 'text', hideOnMobile: true },
    { key: 'amount', label: 'Amount', type: 'money', align: 'right', sortable: true },
    { key: 'status', label: 'Status', type: 'status' },
    { key: 'createdAt', label: 'Created', type: 'datetime', sortable: true },
  ],
  actions: ['view'],
  hasDetail: true,
  empty: { title: 'No Square payments yet.', description: 'Payments appear here after a provider attempt is recorded.' },
  statusKey: 'status',
};
export const ticketPurchasesDefinition: ResourceDefinition = {
  key: 'ticket-purchases',
  label: 'Ticket Purchases',
  singular: 'Ticket Purchase',
  description: 'Ticket holds, confirmation and issued QR tickets.',
  group: 'Payments',
  basePath: '/admin/ticket-purchases',
  apiPath: 'ticket-purchases',
  permission: 'orders',
  titleKey: 'id',
  idPrefix: 'ticket',
  seed: () => [],
  searchFields: ['id', 'customerName', 'customerEmail', 'status'],
  defaultSort: { key: 'createdAt', direction: 'desc' },
  filters: [{ key: 'status', label: 'Status', options: opts(['pending_payment', 'Pending payment'], ['confirmed', 'Confirmed'], ['expired', 'Expired'], ['cancelled', 'Cancelled']) }],
  columns: [
    { key: 'id', label: 'Purchase', type: 'title', sortable: true },
    { key: 'customerEmail', label: 'Customer', type: 'text' },
    { key: 'quantity', label: 'Qty', type: 'text', align: 'center' },
    { key: 'amount', label: 'Amount', type: 'money', align: 'right' },
    { key: 'status', label: 'Status', type: 'status' },
    { key: 'createdAt', label: 'Created', type: 'datetime', sortable: true },
  ],
  actions: ['view'],
  hasDetail: true,
  empty: { title: 'No ticket purchases yet.', description: 'Paid ticket checkouts and active holds appear here.' },
  statusKey: 'status',
};

export const vipBookingsDefinition: ResourceDefinition = {
  key: 'vip-bookings',
  label: 'VIP Bookings',
  singular: 'VIP Booking',
  description: 'Square-backed VIP bookings and booth holds.',
  group: 'Payments',
  basePath: '/admin/vip-bookings',
  apiPath: 'vip-bookings',
  permission: 'orders',
  titleKey: 'id',
  idPrefix: 'vip',
  seed: () => [],
  searchFields: ['id', 'customerName', 'customerEmail', 'status'],
  defaultSort: { key: 'createdAt', direction: 'desc' },
  filters: [{ key: 'status', label: 'Status', options: opts(['pending_payment', 'Pending payment'], ['confirmed', 'Confirmed'], ['expired', 'Expired'], ['cancelled', 'Cancelled']) }],
  columns: [
    { key: 'id', label: 'Booking', type: 'title', sortable: true },
    { key: 'customerEmail', label: 'Customer', type: 'text' },
    { key: 'amount', label: 'Due', type: 'money', align: 'right' },
    { key: 'status', label: 'Status', type: 'status' },
    { key: 'createdAt', label: 'Created', type: 'datetime', sortable: true },
  ],
  actions: ['view'],
  hasDetail: true,
  empty: { title: 'No paid VIP bookings yet.', description: 'Request-only VIP submissions remain in Booking Requests.' },
  statusKey: 'status',
};
